import allEnglishWords from "an-array-of-english-words";

// Curated answer pool — common, recognizable 5-letter words (like real Wordle)
export const ENGLISH_ANSWERS = [
  "about", "above", "abuse", "actor", "acute", "admit", "adopt", "adult",
  "after", "again", "agent", "agree", "ahead", "alarm", "album", "alert",
  "alien", "align", "alike", "alive", "allow", "alone", "along", "alter",
  "among", "angel", "anger", "angle", "angry", "apart", "apple", "apply",
  "arena", "argue", "arise", "array", "aside", "asset", "atlas", "avoid",
  "awake", "award", "aware", "badly", "baker", "basic", "basin", "basis",
  "beach", "beast", "began", "begin", "being", "belly", "bench", "berry",
  "birth", "black", "blade", "blame", "blank", "blast", "blaze", "bleed",
  "blend", "bless", "blind", "block", "blood", "bloom", "blown", "board",
  "bonus", "boost", "bound", "brain", "brand", "brave", "bread", "break",
  "breed", "brick", "brief", "bring", "broad", "broke", "brown", "brush",
  "buddy", "build", "built", "bunch", "burst", "buyer", "cabin", "cable",
  "camel", "candy", "carry", "catch", "cause", "chain", "chair", "chaos",
  "charm", "chart", "chase", "cheap", "check", "cheek", "chest", "chief",
  "child", "chunk", "civic", "claim", "clash", "class", "clean", "clear",
  "clerk", "click", "cliff", "climb", "cling", "clock", "clone", "close",
  "cloth", "cloud", "coach", "coast", "color", "comet", "comic", "coral",
  "count", "court", "cover", "crack", "craft", "crane", "crash", "crazy",
  "cream", "creek", "crest", "crime", "cross", "crowd", "crown", "cruel",
  "crush", "curve", "cycle", "daily", "dance", "death", "debug", "decay",
  "delay", "delta", "demon", "dense", "depot", "depth", "devil", "diary",
  "dirty", "diver", "dizzy", "dodge", "doubt", "dough", "draft", "drain",
  "drama", "drank", "drawn", "dream", "dress", "dried", "drift", "drill",
  "drink", "drive", "drove", "drown", "drunk", "dusty", "eager", "eagle",
  "early", "earth", "eight", "elder", "elect", "elite", "email", "empty",
  "enemy", "enjoy", "enter", "entry", "equal", "error", "essay", "event",
  "every", "exact", "exile", "exist", "extra", "fable", "faith", "false",
  "fancy", "fatal", "fault", "feast", "fence", "fewer", "fiber", "field",
  "fifth", "fifty", "fight", "final", "flame", "flash", "fleet", "flesh",
  "float", "flood", "floor", "flour", "fluid", "flute", "focal", "focus",
  "force", "forge", "forth", "found", "frame", "frank", "fraud", "fresh",
  "front", "froze", "fruit", "fully", "funny", "giant", "given", "glass",
  "globe", "gloom", "glory", "glove", "going", "grace", "grade", "grain",
  "grand", "grant", "grape", "grasp", "grass", "grave", "great", "greed",
  "green", "greet", "grief", "grind", "groan", "groom", "gross", "group",
  "grove", "grown", "guard", "guess", "guest", "guide", "guild", "guilt",
  "habit", "happy", "harsh", "haunt", "heart", "heavy", "hedge", "hello",
  "herbs", "hinge", "hobby", "honey", "honor", "horse", "hotel", "house",
  "human", "humor", "hurry", "ideal", "image", "imply", "index", "inner",
  "input", "irony", "issue", "ivory", "jewel", "joint", "joker", "judge",
  "juice", "jumbo", "karma", "kayak", "knack", "kneel", "knife", "knock",
  "known", "label", "lance", "large", "laser", "later", "laugh", "layer",
  "learn", "lease", "leave", "legal", "lemon", "level", "lever", "light",
  "limit", "linen", "liver", "local", "lodge", "logic", "loose", "lover",
  "lower", "loyal", "lucky", "lunch", "lying", "magic", "major", "maker",
  "manor", "march", "match", "mayor", "medal", "media", "mercy", "merge",
  "merit", "merry", "metal", "meter", "might", "miner", "minor", "minus",
  "mixed", "model", "money", "month", "moral", "motor", "mount", "mouse",
  "mouth", "movie", "muddy", "music", "naive", "nerve", "never", "noble",
  "noise", "north", "noted", "novel", "nurse", "ocean", "offer", "often",
  "olive", "onset", "opera", "orbit", "order", "organ", "other", "outer",
  "oxide", "ozone", "paint", "panel", "panic", "patch", "pause", "peace",
  "peach", "pearl", "penny", "phase", "phone", "photo", "piano", "piece",
  "pilot", "pinch", "pixel", "pizza", "place", "plain", "plane", "plant",
  "plate", "plaza", "plead", "plumb", "point", "polar", "pound", "power",
  "press", "price", "pride", "prime", "print", "prior", "prize", "probe",
  "proof", "prose", "proud", "prove", "proxy", "pulse", "pupil", "queen",
  "quest", "queue", "quick", "quiet", "quite", "quota", "quote", "radar",
  "radio", "raise", "rally", "range", "rapid", "ratio", "reach", "realm",
  "rebel", "refer", "reign", "relax", "reply", "rider", "ridge", "rifle",
  "right", "rigid", "risky", "rival", "river", "robin", "robot", "rocky",
  "rough", "round", "route", "royal", "rugby", "ruler", "rural", "sadly",
  "saint", "salon", "sauce", "scale", "scene", "scope", "score", "sense",
  "serve", "setup", "seven", "shade", "shall", "shame", "shape", "share",
  "shark", "sharp", "sheep", "sheer", "shelf", "shell", "shift", "shine",
  "shirt", "shock", "shore", "short", "shout", "shown", "sight", "silly",
  "since", "sixth", "sixty", "skate", "skill", "skull", "slate", "sleep",
  "slice", "slide", "slope", "smart", "smell", "smile", "smoke", "snack",
  "snake", "solar", "solid", "solve", "sorry", "sound", "south", "space",
  "spare", "spark", "speak", "speed", "spend", "spent", "spice", "spine",
  "spoke", "spoon", "sport", "spray", "squad", "stack", "staff", "stage",
  "stake", "stale", "stall", "stand", "stare", "start", "state", "steak",
  "steam", "steel", "steep", "steer", "stern", "stick", "still", "stock",
  "stone", "stood", "store", "storm", "story", "stove", "strap", "straw",
  "strip", "stuck", "study", "stuff", "style", "sugar", "suite", "sunny",
  "super", "surge", "swamp", "swear", "sweat", "sweep", "sweet", "swept",
  "swift", "swing", "sword", "swore", "sworn", "swung", "table", "taken",
  "taste", "teach", "teeth", "thank", "theme", "thick", "thief", "thing",
  "think", "third", "those", "three", "threw", "throw", "thumb", "tight",
  "timer", "tired", "title", "today", "token", "topic", "total", "touch",
  "tough", "towel", "tower", "toxic", "trace", "track", "trade", "trail",
  "train", "trait", "trash", "treat", "trend", "trial", "tribe", "trick",
  "tried", "troop", "truck", "truly", "trunk", "trust", "truth", "tulip",
  "twice", "twist", "ultra", "under", "unify", "union", "unite", "unity",
  "until", "upper", "upset", "urban", "usage", "usual", "utter", "valid",
  "value", "valve", "vault", "venue", "verse", "video", "vigor", "vinyl",
  "viral", "virus", "visit", "vital", "vivid", "vocal", "vodka", "voice",
  "voter", "wagon", "waste", "watch", "water", "weary", "weave", "wedge",
  "weigh", "weird", "whale", "wheat", "wheel", "where", "which", "while",
  "whirl", "white", "whole", "whose", "widen", "widow", "width", "witch",
  "woman", "world", "worry", "worse", "worst", "worth", "would", "wound",
  "wrath", "write", "wrong", "wrote", "yacht", "yield", "young", "youth",
  "zebra",
];

// Full dictionary of valid 5-letter English words for guess validation (~12k words)
export const VALID_ENGLISH_GUESSES: Set<string> = new Set(
  allEnglishWords.filter((w: string) => w.length === 5).map((w: string) => w.toUpperCase())
);

// Seeded daily word picker — same word for everyone on the same day
const EPOCH = new Date(2024, 0, 1).getTime(); // Jan 1 2024
export function getDailyWordIndex(answers: string[]): number {
  const now = new Date();
  const daysSinceEpoch = Math.floor((now.getTime() - EPOCH) / 86400000);
  return daysSinceEpoch % answers.length;
}

export function getDailyWord(): string {
  return ENGLISH_ANSWERS[getDailyWordIndex(ENGLISH_ANSWERS)].toUpperCase();
}
